//
export const OPEN_MODAL_REGISTER = "OPEN_MODAL_REGISTER";
//
export const OPEN_MODAL_ADD_ACCOUNT_LOGIN = "OPEN_MODAL_ADD_ACCOUNT_LOGIN";
//
export const CLOSE_MODAL = "CLOSE_MODAL";
//
export const UPDATE_POPOVER = "UPDATE_POPOVER";
//
export const LOADING_MODAL = "LOADING_MODAL";
//
export const OPEN_MODAL_LOGIN = "OPEN_MODAL_LOGIN";
//
export const OPEN_MODAL_POST = "OPEN_MODAL_POST";
//
export const OPEN_MODAL_PREVIEW_AVATAR = "OPEN_MODAL_PREVIEW_AVATAR";
//