//
export const UPDATE_DATA = "UPDATE_DATA";
//
export const OPEN_MODAL_LOCAL = "OPEN_MODAL_LOCAL";
//
export const OPEN_MODAL_FEEL = "OPEN_MODAL_FEEL";
//
export const OPEN_MODAL_TAG = "OPEN_MODAL_TAG";
//
export const RETURN_MODAL_POST = "RETURN_MODAL_POST";
//
export const OPEN_MODAL_CHOOSE_BACKGROUND = "OPEN_MODAL_CHOOSE_BACKGROUND";
//
export const OPEN_MODAL_IMAGE_VIDEO_EDIT = "OPEN_MODAL_IMAGE_VIDEO_EDIT";
//
export const OPEN_MODAL_ANSWER_QUESTION = "OPEN_MODAL_ANSWER_QUESTION";
//
export const UPDATE_DATA_FULL = 'UPDATE_DATA_FULL';